### ISSUE TITLE
org.openrewrite.java.ChangeType not working on `Groovy` or `Kotlin`

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite#2961] opened 2023-03-10 13:21 UTC
`org.openrewrite.java.ChangeType` should be working on Kotlin sources according to Slack conversation, but this is not the case.

https://rewriteoss.slack.com/archives/C01A843MWG5/p1678437393167559?thread_ts=1678436521.463349&cid=C01A843MWG5

Test by `/gradlew :sample:rewriteDryRun`, reproducible:  https://github.com/nomisRev/rewrite-arrow/pull/4

**Comment by traceyyoshima** [comment] 2023-03-10 19:46
ChangeType does not apply to non-`J` CompilationUnits, because visitJavaSourceFile is overridden. The override prevents either `G` or `K` methods from visiting the CompilationUnit.

```
    @Override
    public J visitJavaSourceFile(JavaSourceFile cu, P p) {
        return cu instanceof K.CompilationUnit ? visitCompilationUnit((K.CompilationUnit) cu, p) : cu;
    }
```

The base changes are easily fixed by using `visitSourceFile` in `ChangeTypeVisitor` without any regressions.
However, we'll need to investigate how to apply the `ChangeClassDefinition` visitor to `G` and `K` so update class definitions and SourceFile paths.

**Comment by nomisRev** [comment] 2023-03-10 20:14
I think other recipes such as `org.openrewrite.java.ChangePackage` also suffer from this, but haven't been able to confirm. Would the suggested investigation address that also? Or could this be a recurring issue to these kind of Java recipes?

**Comment by traceyyoshima** [comment] 2023-03-10 21:44
> I think other recipes such as `org.openrewrite.java.ChangePackage` also suffer from this, but haven't been able to confirm. Would the suggested investigation address that also? Or could this be a recurring issue to these kind of Java recipes?

Yes, that's right! The issue will occur on any java recipe that overrides `visitSourceFile.`

There are a few issues in ChangeType that don't translate well across languages - I.E. ChangeType prevents adding imports of types that are implicitly available in java via `java. lang`. `Kotlin` would require its implicit imports in addition to `java.lang`, and I'm not sure about `Groovy.`

Using visitors to preserve most of the functionality is relatively simple, but `ChangeClassDefinition` and `Imports` look more complex.

**Comment by traceyyoshima** [comment] 2023-03-14 01:21
@nomisRev, the changes are in review -- I have changes ready for `Kotlin` to enable `ChangeType` in `K` after review/merge.

Note:
Filtering out `Kotlin` imports won't be immediately available in K, and that will be up to the user for now.
I.E., ChangeType from `kotlin.Int` to `kotlin.Long`, will currently add the import for `kotlin.Long`.

I have a solution in mind, but I need to discuss it with the team first.

**Comment by nomisRev** [comment] 2023-03-14 07:59
Awesome! Thanks for letting me know, looking forward to testing it 🙌 Would this also apply to `ChangePackage`?

**Comment by traceyyoshima** [comment] 2023-03-14 15:48
> Awesome! Thanks for letting me know, looking forward to testing it 🙌 Would this also apply to `ChangePackage`?

Still waiting. I'll apply reviewed changes to `ChangePackage` in a separate issue. It should be quick, but I haven't looked at the recipe in a while and am unsure what will be required. I'll tag you when `ChangePackage` works in other languages.

**Closed** 2023-03-14 17:10 UTC
Labels: bug
