### ISSUE TITLE
Recipe: Test does not run with `ReplaceConstant`.

### ISSUE THREAD

**Issue by dianamaesan** [openrewrite/rewrite#1752] opened 2022-05-03 15:49 UTC
Hello,

I want to use your recipe `ReplaceConstant`. 

Problem:  When I pass my test it does not work with your recipe, I would like to understand why, also your recipe is not making changes in my project.  Any idea?. 

I attach the test I had developed for test your recipe. 

Version:

``` xml
<rewrite.version>7.20.0</rewrite.version>
<rewrite-maven-plugin.version>4.21.0</rewrite-maven-plugin.version>
```

With latest version I have another issues
``` xml
<rewrite.version>7.22.0</rewrite.version>
<rewrite-maven-plugin.version>4.23.0</rewrite-maven-plugin.version>
``` 
![image](https://user-images.githubusercontent.com/91873174/166488336-8a28905a-530a-4255-97ae-5588dbc3de0d.png)

Thanks so much,

``` java
class ReplaceStaticConstantByLiteralTest : JavaRecipeTest {
   companion object {
        private val b: String = """
            package com.constant;
            public class B {
               public static final String VAR = "default";
            }
        """.trimIndent();
    }

    @Test
    fun replaceConstant() = assertChanged(
        dependsOn = arrayOf(b),
        recipe = ReplaceConstant("com.constant.B", "VAR", "\"newValue\""),
        before = """
            package com.abc;
            import com.constant.B;
            class A {
              String v = B.VAR;
            }
            """,
        after = """
            package com.abc;
            class A {
                String v = "newValue";
            }
        """,
    )
}
```
Error:
`Caused by: java.lang.ClassCastException: class org.openrewrite.java.tree.J$Literal cannot be cast to class org.openrewrite.java.tree.J$Identifier (org.openrewrite.java.tree.J$Literal and org.openrewrite.java.tree.J$Identifier are in unnamed module of loader 'app')
`

**Comment by traceyyoshima** [comment] 2022-05-03 19:20
Hi @dianamaesan, thank you for reporting the issue!

I'm having trouble reproducing the `java.lang in response to the first error.NoSuchMethodError: 'java.io.InputStream org.openrewrite.Parser$Input.getSource()'` error. I've run both `rewrite-maven-plugin.version` `7.21.0` and `7.23.0` without issues.

Are there any additional configurations in the plugin I should be aware of?


> Caused by: java.lang.ClassCastException: class org.openrewrite.java.tree.J$Literal cannot be cast to class org.openrewrite.java.tree.J$Identifier (org.openrewrite.java.tree.J$Literal and org.openrewrite.java.tree.J$Identifier are in unnamed module of loader 'app')

I've identified the cause of the error and have a fix ready, but I'd like to ask a few questions before committing the changes.

I have a few questions:

1. Will resolving the `java.lang.ClassCastException` resolve this issue for you?
2. If the `NoSuchMethodError` is still a problem, would you mind if we separate that into a different issue?

Thanks in advance!

**Comment by dianamaesan** [comment] 2022-05-04 07:22
Hi @traceyyoshima!!,

Thank you very much for your quick response to my question. I answer your questions below:

_Are there any additional configurations in the plugin I should be aware of?_

> No, there are no additional configurations.

_Will resolving the `java.lang.ClassCastException` resolve this issue for you?_

> Yes, it solves my problem.

_If the `NoSuchMethodError` is still a problem, would you mind if we separate that into a different issue?_

>Of course I don't mind if a different topic is opened.

Thank you!

**Comment by traceyyoshima** [comment] 2022-05-04 17:02
> Will resolving the `java.lang.ClassCastException` resolve this issue for you?

Great, I'm glad it will resolve the issue!

> Of course I don't mind if a different topic is opened.

Thank you, I appreciate your understanding, I'll commit the changes and reference this issue as fixed.
Please let us know if you experience the `NoSuchMethodError` again, I'll also keep an eye out for any other reports of a similar problem.

**Closed** 2022-05-04 17:40 UTC
Labels: bug, question
