### ISSUE TITLE
`ReplaceDuplicateStringLiterals` is not making changes to source files it should

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#2312] opened 2022-10-18 00:28 UTC
The design partner reported 20 examples where they feel the recipe should have replaced the same string literal. 

"The description of the recipe, I understand that if a string has 5 or more characters and is repeated 3 times or more, the recipe should create a final string."

**Comment by tkvangorder** [comment] 2022-10-18 00:29
@traceyyoshima I saw this behavior on the tenant SaaS and this was not in a test class.

**Comment by traceyyoshima** [comment] 2022-10-21 19:01
Closing the issue, because we confirmed the problem was not in the Recipe, but related to classloading else where.

**Closed by traceyyoshima** 2022-10-21 19:01 UTC
Labels: bug, design-partner-1
