### ISSUE TITLE
Support template-based recipes

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#2606] opened 2023-01-06 06:57 UTC
It would be useful to have a generic recipe, which can be used declaratively (i.e. using YAML) to achieve simple refactorings like for example JUnit `assertEquals(expected, actual)` to AssertJ `assertThat(actual).isEqualTo(expected)`. The idea would be to both use templates to match the input LST as well as for producing the target LST. This could be very useful to the occasional recipe author writing simple recipes, as only the template language needs to be understood. I think some recipes may also get easier to grok with this approach.

Just as an idea, for the example given above the input template could maybe look something like this:
```java
org.junit.jupiter.api.Assertions.assertEquals(#{expected:any()}, #{actual:any()})
```
and the corresponding output template then something like (here without type attribution assuming the recipe could fill that in based on the input template):
```java
org.assertj.core.api.Assertions.assertThat(#{actual}).isEqualTo(#{expected})
```

Here is a (probably incomplete) list of tasks to achieve this:
- [ ] Assuming the current template mechanism can be extended, what is missing?
  - [ ] Support named parameters so that the elements can be extracted from the template matched against the input and then
  - [ ] Not all parts of the input may be type attributed and would instead require by-name matching
  - [ ] The elements to be extracted from the input may also have to match some given regular expression (possibly in addition to the type being matched); e.g. `assertTrue(#{e:any(java.util.regex.Matcher),text(name.*)}.matches())` would match any `assertTrue()` calls, where the textual representation of the argument starts with `name` and it is of type `Matcher`
- [ ] Will the input template require synthesizing the before and after code "out of thin air" so that it can be processed?
  - There could be insertion point coordinate-specific templates for this
problem? May this require type attribution like e.g. `#{receiver:any():this}.#{m:any(java.util.List):foo()}`?
- [ ] Map LST corresponding to input template to a visitor
- [ ] Support extracting referenced types from the application of a Java template, so that these can optionally be imported (using `maybeAddImport()`)
- [ ] Check if the replacement coordinates are required as input or if that can somehow automatically be derived from the template

In a first step I would like to prototype this for method invocation refactorings, but I think this idea could in the future also be leveraged for other refactorings and possibly also for languages other than Java.

**Comment by bvolpato** [comment] 2023-01-06 21:29
+1.

Refaster has this approach: https://errorprone.info/docs/refaster

It is much more limited, but works for a lot of simple cases.

**Comment by knutwannheden** [comment] 2023-01-06 23:48
Yes, I also like Refaster. I think having textual templates can however also be a nice alternative, especially to match against the LST on the input side.

**Comment by tkvangorder** [comment] 2023-01-10 00:07
I would worry about the scope of the input template language. You would likely need to add elements to represent method invocations (as in this example), identifiers, blocks, method declarations, etc. I understand the benefit of making simple transformations via a declarative approach, it just can be a slippery slope. 

Looping in @jkschneider and @sambsnyd to get their feedback

**Comment by rpau** [comment] 2023-05-23 17:24
I believe that this ticket is a duplicate of https://github.com/openrewrite/rewrite/issues/3110. @knutwannheden feel free to re-open it if you disagree.

**Closed by rpau** 2023-05-23 17:24 UTC
Labels: enhancement
