### ISSUE TITLE
StringIndexOutOfBoundsException in TabsAndIndentsVisitor.shift

### ISSUE THREAD

**Issue by ylemoigne** [openrewrite/rewrite#3821] opened 2023-12-14 18:55 UTC
## What version of OpenRewrite are you using?
Gradle plugin 6.6.1

And :
implementation("org.openrewrite:rewrite-core:8.11.2")
implementation("org.openrewrite:rewrite-java-11:8.11.2")

## How are you running OpenRewrite?
gradle, applied as a plugin on some module of a multimodule project.

## What is the smallest, simplest way to reproduce the problem?
./gradlew rewriteRun

## What did you expect to see?
No error

## What is the full stack trace of any errors you encountered?
```
Execution failed for task ':server:rewriteRun'.
> java.lang.RuntimeException: Error while visiting subproject/src/main/java-generated-protected/foo/Bar.java: java.lang.StringIndexOutOfBoundsException: start 3, end 1, length 1
    java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1724)
    java.base/java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:863)
    java.base/java.lang.StringBuilder.delete(StringBuilder.java:288)
    org.openrewrite.java.format.TabsAndIndentsVisitor.shift(TabsAndIndentsVisitor.java:573)
    org.openrewrite.java.format.TabsAndIndentsVisitor.indent(TabsAndIndentsVisitor.java:547)
    org.openrewrite.java.format.TabsAndIndentsVisitor.indentTo(TabsAndIndentsVisitor.java:418)
    org.openrewrite.java.format.TabsAndIndentsVisitor.visitSpace(TabsAndIndentsVisitor.java:178)
    org.openrewrite.java.JavaVisitor.visitEmpty(JavaVisitor.java:537)
    ...
```

**Comment by timtebeek** [comment] 2023-12-14 20:02
Hi @ylemoigne ; thanks for trying out the latest version released today before reporting your issue here; really appreciated!

I'm looking at the stacktrace and the associated class, but I'm not seeing any recent changes there that might factor in:
https://github.com/openrewrite/rewrite/commits/v8.11.2/rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java

A couple of questions as I don't yet have enough of a lead to troubleshoot this.
- Is there any indication of what file it stumbles over?
- Would you be able to share part of that file with us?
- Is there any style configuration on your part that might factor in?
- And what recipe did you run to trigger this?

**Comment by ylemoigne** [comment] 2023-12-14 20:10
Hi @timtebeek 

Yes there is an indication of what is the java source file but sadly, I'm not able to share it with anyone (legal stuff).

No style, here the whole config I'm using : 
```
rewrite {
    activeRecipe("org.openrewrite.java.RemoveUnusedImports")
    activeRecipe("org.openrewrite.java.OrderImports")
}
```

I know that without the file that raise this issue it's hard to debug for you, I'm sorry.

**Comment by ylemoigne** [comment] 2023-12-14 21:00
I'm not sure how it works. 

If I try to replace the string in `multipleClassesWithTheSameNameButDifferentPackages` to 
```
java(
            """
              package foo;
              
              public class Toto extends Foo {
              }
              """
          )
```

The test already fail.
```
java.lang.IllegalStateException: LST contains missing or invalid type information
Identifier->ClassDeclaration->CompilationUnit
/*~~(Identifier type is missing or malformed)~~>*/Foo
	at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:87)
```

It seems that it need to know all dependencies. If it's true, I don't know how to provide it. (And I hope that's not too hard, the source file causing issue is 1600 lines long and have a lot of dependend types 😅 )

**Comment by knutwannheden** [comment] 2023-12-14 21:34
To fix that particular problem you can just disable all type validation like so: https://github.com/openrewrite/rewrite/blob/0c7f396a42c7f43c40f2d35186736829a76f1c7c/rewrite-java-test/src/test/java/org/openrewrite/java/format/MethodParamPadTest.java#L333

**Comment by timtebeek** [comment] 2023-12-14 21:35
Perhaps it helps to ignore type validation options for your recipe, although that would also affect the remove imports recipe.

```java
 @Test 
 void foo() { 
     rewriteRun(
       spec -> spec.recipe(new RemoveUnusedImports()).typeValidationOptions(TypeValidation.none()),
       java( 
         """ 
           import java.awt.List; 
           import java.util.List; 
                          
           class Test {} 
           """ 
       ) 
     ); 
 }
```

**Comment by ylemoigne** [comment] 2023-12-15 07:03
On my project, the minimal setup to have the exception is :
```kotlin
rewrite {
    activeRecipe("org.openrewrite.java.OrderImports")
}
```

So in `OrderImportsTest`, I wrote :
```java
    @Issue("https://github.com/openrewrite/rewrite/issues/3821")
    @Test
    void unidenfiedIssue() {
        String content;
        try {
            content = Files.readString(
              Paths.get("/pathTo/Culprit.java"), // Culprit designated by "Error while visiting `theClassFullyQualifiedName`"
              StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }

        rewriteRun(
          spec -> spec.typeValidationOptions(TypeValidation.none()),
          java(content)
        );
    }
```

The test run end with `The recipe must not make changes to ...`

I don't understand why it don't crash before in the the test.
I have checked out the `v8.11.2` tag (commit: cba6919d), I've run the test with the same JVM I use to build my projet (temurin 11)

I don't know how to go further :/

**Comment by knutwannheden** [comment] 2024-01-21 17:20
@ylemoigne Maybe you manage to strip it down to some code which you then can anonymize and share. In a unit test you can maybe set a breakpoint on the exception to help figure it out. Based on the stack trace it looks like you have an empty parenthesis or curly braces in your code somewhere with line breaks between the opening and closing character. So something like:
```
{
   }
```
Maybe this helps you figure it out.

**Comment by ylemoigne** [comment] 2024-02-17 18:17
Sorry for the lack of news. I'm still intend to help but not have much spare time now.

**Comment by timtebeek** [comment] 2024-09-21 21:03
Given how much time has passed since I'm regretfully going to close this one as can not be reproduced. Feel free to chime in if there's a public set of steps to make this fail, such that we can look into a fix.

**Closed by timtebeek** 2024-09-21 21:03 UTC
Labels: bug, question
