### ISSUE TITLE
Incorrect glob pattern matching

### ISSUE THREAD

**Issue by Wallman** [openrewrite/rewrite#3658] opened 2023-11-02 15:31 UTC
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.8.3

## How are you running OpenRewrite?

Unit test

## What is the smallest, simplest way to reproduce the problem?

```java
assertThat(matchesGlob(path("a-test/test.txt"), "**/*-test/*-test/test.txt")).isFalse();
```
is failing. See [PR](https://github.com/openrewrite/rewrite/pull/3657).

It incorrectly overmatches the path `a-test/test.txt` from the glob pattern `**/*-test/*-test/test.txt`.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

The [code](https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/PathUtils.java#L84-L189) for this looks hard to dig in to!

Should rewrite use a [standard library](https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)) for this instead?

**Comment by Wallman** [comment] 2023-11-02 15:32
@shanman190

**Comment by shanman190** [comment] 2023-11-03 00:08
It's definitely possible to switch to `PathMatcher`. The only thing is that the incoming Path would need to be normalized for the current operating system. For the OSS components, the OpenRewrite LST is built and executed upon on the same machine. However, when using the Moderne SaaS or Moderne CLI, it is possible that the LST was generated on an operating system that is _different_ from the current one and since the `PathMatcher` implementations are OS specific, they would fail to match if done without this preceding normalization step.

**Comment by Wallman** [comment] 2023-11-03 08:31
Oh I understand! Do you have an idea how to solve the bug without PathMatcher?

**Comment by shanman190** [comment] 2023-11-03 14:40
So I believe the bug is a simple `<` VS `<=` found right here:
https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/PathUtils.java#L139

To walk through the data flow:

1. Break path and pattern into tokens and start processing from the beginning of both.
2. Encounter `**` and switch to processing from the end.
3. Consume all of the path tokens, leaving two pattern tokens.
4. Enter the loop linked and check only the all, but the last pattern token. In this case the first pattern token IS `**`, but we fail to check the second (and last) pattern token due to the bug of `<` VS `<=`. If we had checked it, then it would have returned false as intended.

**Comment by Wallman** [comment] 2023-11-03 14:45
Good catch! I tried it locally which makes all tests green :) Do you want to add the contribution or should I add it [here](https://github.com/openrewrite/rewrite/pull/3657) ?

**Comment by shanman190** [comment] 2023-11-03 14:47
By all means, feel free to add it as a contribution to the existing PR and we can get it merged in. 🙂

**Closed** 2023-11-03 17:25 UTC
Labels: bug
