### ISSUE TITLE
AnnotationMatcher does not match fully qualified argument types

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#337] opened 2021-03-01 16:22 UTC
The `AnnotationMatcher` was extracted from `FindAnnotations` which may have a different use case than recipes finding  annotations by argument type.  

e.g. [rewrite-spring SpringRunnerToSpringExtension](https://github.com/openrewrite/rewrite-spring/blob/master/src/main/java/org/openrewrite/java/spring/boot2/SpringRunnerToSpringExtension.java) use 'SemanticallyEqual` along with a fairly complex configuration which distracts from the recipes intended purpose.

**Comment by jkschneider** [comment] 2021-03-10 02:36
Duplicate of #357

**Closed by jkschneider** 2021-03-10 02:36 UTC
Labels: enhancement
