### ISSUE TITLE
Failure with Maven CI friendly versioning; unresolved placeholder in download URL

### ISSUE THREAD

**Issue by famod** [openrewrite/rewrite#3022] opened 2023-03-23 11:03 UTC
When running `curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio`, I'm getting the following error in one of my modules (and only in that one!):
```
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.41.0:run (default-cli) on project register-archive-server: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.41.0:run failed: Illegal character in path at index 81: file:///home/famod/.m2/repository/somecompany/someproject/register-archive-parent/${revision}.${changelist}-dev3/register-archive-parent-${revision}.${changelist}-dev3.pom -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.41.0:run (default-cli) on project register-archive-server: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.41.0:run failed: Illegal character in path at index 81: file:///home/famod/.m2/repository/somecompany/someproject/register-archive-parent/${revision}.${changelist}-dev3/register-archive-parent-${revision}.${changelist}-dev3.pom
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.41.0:run failed: Illegal character in path at index 81: file:///home/famod/.m2/repository/somecompany/someproject/register-archive-parent/${revision}.${changelist}-dev3/register-archive-parent-${revision}.${changelist}-dev3.pom
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 81: file:///home/famod/.m2/repository/somecompany/someproject/register-archive-parent/${revision}.${changelist}-dev3/register-archive-parent-${revision}.${changelist}-dev3.pom
    at java.net.URI.create (URI.java:906)
    at org.openrewrite.maven.internal.MavenPomDownloader.download (MavenPomDownloader.java:487)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPropertiesAndRepositoriesRecursively (ResolvedPom.java:353)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentsRecursively (ResolvedPom.java:310)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolve (ResolvedPom.java:299)
    at org.openrewrite.maven.tree.ResolvedPom.resolve (ResolvedPom.java:144)
    at org.openrewrite.maven.tree.Pom.resolve (Pom.java:104)
    at org.openrewrite.maven.MavenParser.parseInputs (MavenParser.java:105)
    at org.openrewrite.Parser.parse (Parser.java:41)
    at org.openrewrite.maven.MavenMojoProjectParser.parseMaven (MavenMojoProjectParser.java:311)
    at org.openrewrite.maven.MavenMojoProjectParser.listSourceFiles (MavenMojoProjectParser.java:120)
    at org.openrewrite.maven.AbstractRewriteMojo.listResults (AbstractRewriteMojo.java:272)
    at org.openrewrite.maven.AbstractRewriteRunMojo.execute (AbstractRewriteRunMojo.java:53)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.net.URISyntaxException: Illegal character in path at index 81: file:///home/famod/.m2/repository/somecompany/someproject/register-archive-parent/${revision}.${changelist}-dev3/register-archive-parent-${revision}.${changelist}-dev3.pom
    at java.net.URI$Parser.fail (URI.java:2974)
    at java.net.URI$Parser.checkChars (URI.java:3145)
    at java.net.URI$Parser.parseHierarchical (URI.java:3227)
    at java.net.URI$Parser.parse (URI.java:3175)
    at java.net.URI.<init> (URI.java:623)
    at java.net.URI.create (URI.java:904)
    at org.openrewrite.maven.internal.MavenPomDownloader.download (MavenPomDownloader.java:487)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPropertiesAndRepositoriesRecursively (ResolvedPom.java:353)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentsRecursively (ResolvedPom.java:310)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolve (ResolvedPom.java:299)
    at org.openrewrite.maven.tree.ResolvedPom.resolve (ResolvedPom.java:144)
    at org.openrewrite.maven.tree.Pom.resolve (Pom.java:104)
    at org.openrewrite.maven.MavenParser.parseInputs (MavenParser.java:105)
    at org.openrewrite.Parser.parse (Parser.java:41)
    at org.openrewrite.maven.MavenMojoProjectParser.parseMaven (MavenMojoProjectParser.java:311)
    at org.openrewrite.maven.MavenMojoProjectParser.listSourceFiles (MavenMojoProjectParser.java:120)
    at org.openrewrite.maven.AbstractRewriteMojo.listResults (AbstractRewriteMojo.java:272)
    at org.openrewrite.maven.AbstractRewriteRunMojo.execute (AbstractRewriteRunMojo.java:53)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
```

This `archive-server` module is located in `archive/server`. The other two modules where a Quarkus app is built (not sure this matters) are located in `server` and `testdata-server` and those two are not failing! So the nesting depth might be relevant?
Then again there are two other simple lib-like modules under `archive/` that don't fail. There are even more modules next to `server` and `testdata-server` that don't fail either.

pom-xml setup is as follows:
`archive/server/pom.xml`:
```xml
    <parent>
        <groupId>somecompany.someproject</groupId>
        <artifactId>register-archive-parent</artifactId>
        <version>${revision}.${changelist}${sha1}</version>
    </parent>
    <artifactId>register-archive-server</artifactId>
```

`archive:`
```xml
    <parent>
        <groupId>somecompany.someproject</groupId>
        <artifactId>register-parent</artifactId>
        <version>${revision}.${changelist}${sha1}</version>
    </parent>
    <artifactId>register-archive-parent</artifactId>
```

root parent (has no parent):
```xml
    <groupId>somecompany.someproject</groupId>
    <artifactId>register-parent</artifactId>
    <version>${revision}.${changelist}${sha1}</version>
    <packaging>pom</packaging>
<!-- ... -->
    <properties>
        <revision>4.2.0</revision>
        <changelist>local</changelist>
        <sha1></sha1>   <!-- can be used locally as a discriminator to keep multiple clones separated -->
<!-- ... -->
```
`sha1` is set via `export MAVEN_OPTS="${MAVEN_OPTS} -Dsha1=-dev3"` (in `.envrc` for `direnv`, but that shouldn't matter`).

I cannot share the project (closed source) and so far I haven't been able to create a reproducer.

Any thoughts? @nmck257 maybe?

/cc @gsmet

**Comment by famod** [comment] 2023-03-23 11:07
Btw, I can see `flatten-maven-plugin:1.3.0:flatten` being executed in the lifecycle forked by openrewrite.
Using Maven 3.8.8.

**Comment by knutwannheden** [comment] 2023-03-23 11:58
@famod Thanks for the report! It looks like OpenRewrite is having issues with the [Maven CI friendly version properties](https://maven.apache.org/maven-ci-friendly.html) in the parent `<version>` element. We will investigate this and keep you posted.

**Comment by nmck257** [comment] 2023-03-23 14:01
yeah, this has been my bane for many months (#2049), and new occurrences of the issue keep waiting until *just* after I've forgotten everything about it.

@famod can you also share the `parent` elements for some of the other (working) modules, for comparison?

**Comment by famod** [comment] 2023-03-23 14:12
@nmck257 
> @famod can you also share the `parent` elements for some of the other (working) modules, for comparison?

Sure, but that's the thing: there is no difference!

`archive/shared/pom.xml`
```xml
    <parent>
        <groupId>somecompany.someproject</groupId>
        <artifactId>register-archive-parent</artifactId>
        <version>${revision}.${changelist}${sha1}</version>
    </parent>
    <artifactId>register-archive-shared</artifactId>
```

`server/pom.xml`
```xml
    <parent>
        <groupId>somecompany.someproject</groupId>
        <artifactId>register-parent</artifactId>
        <version>${revision}.${changelist}${sha1}</version>
    </parent>
    <artifactId>register-server</artifactId>
```

Maybe related, maybe not: the failing `archive/server` module depends on `archive/shared` (and other modules outside of `archive`, e.g. `common`).
We also have a couple of inter-module `test-jar` dependencies, but that shouldn't be relevant either.

**Comment by nmck257** [comment] 2023-03-23 14:23
- are you running the recipe from the root of the project, or the root of the `archive/server` module?
- is `archive/server` the only thing with a dependency on `archive/shared`? the issue could be occurring when the pom-resolution "stack" is ProjectPomA -> ProjectPomB (who's parent is another project pom referenced via CI-friendly versions) -> ProjectPomB's Parent

**Comment by nmck257** [comment] 2023-03-24 14:42
hmm -- yeah, if you're able to isolate this into a test project / `RewriteTest` case which reproduces the issue, then that should do the most to help get to a fix

**Comment by pjotteri** [comment] 2023-04-01 08:42
A version range in parent also fails in similar way.
```
    <parent>
        <groupId>anothercompany</groupId>
        <artifactId>our-parent</artifactId>
	<version>[3.0.0,3.0.5)</version>
    </parent>
```

causes :

`Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.42.0:run failed
`
```
...

Caused by: java.net.URISyntaxException: Illegal character in path at index 58: file:///Users/me/.m2/repository/anothercompany/our-parent/[3.0.0,3.0.5)/our-parent-[3.0.0,3.0.5).pom
    at java.net.URI$Parser.fail (URI.java:2873)
    at java.net.URI$Parser.checkChars (URI.java:3046)
    at java.net.URI$Parser.parseHierarchical (URI.java:3130)
    at java.net.URI$Parser.parse (URI.java:3078)
    at java.net.URI.<init> (URI.java:588)
    at java.net.URI.create (URI.java:850)
    at org.openrewrite.maven.internal.MavenPomDownloader.download (MavenPomDownloader.java:487)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPropertiesAndRepositoriesRecursively (ResolvedPom.java:353)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPropertiesAndRepositoriesRecursively (ResolvedPom.java:364)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentsRecursively (ResolvedPom.java:310)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolve (ResolvedPom.java:299)
    at org.openrewrite.maven.tree.ResolvedPom.resolve (ResolvedPom.java:144)
    at org.openrewrite.maven.tree.Pom.resolve (Pom.java:104)
    at org.openrewrite.maven.MavenParser.parseInputs (MavenParser.java:105)
    at org.openrewrite.Parser.parse (Parser.java:41)
    at org.openrewrite.maven.MavenMojoProjectParser.parseMaven (MavenMojoProjectParser.java:350)

```

Parent version is not resolved before it is used?

**Comment by knutwannheden** [comment] 2023-04-01 09:17
@pjotteri In the upcoming release this case should be fixed: openrewrite/rewrite#3023

**Comment by pjotteri** [comment] 2023-04-01 09:43
Nice, Thanks.

**Comment by sambsnyd** [comment] 2023-04-08 01:00
Closing this as a release with @knutwannheden 's fix is now available. Let us know if it is still a problem

**Closed by sambsnyd** 2023-04-08 01:00 UTC
Labels: bug, question

**Comment by famod** [comment] 2023-04-12 15:39
Trace looks a bit different now:
```
[...]
Caused by: java.net.URISyntaxException: Illegal character in path at index 73: [...]
    at java.net.URI$Parser.fail (URI.java:2974)
    at java.net.URI$Parser.checkChars (URI.java:3145)
    at java.net.URI$Parser.parseHierarchical (URI.java:3227)
    at java.net.URI$Parser.parse (URI.java:3175)
    at java.net.URI.<init> (URI.java:623)
    at java.net.URI.create (URI.java:904)
    at org.openrewrite.maven.internal.MavenPomDownloader.download (MavenPomDownloader.java:487)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPom (ResolvedPom.java:413)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPropertiesAndRepositoriesRecursively (ResolvedPom.java:353)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentsRecursively (ResolvedPom.java:310)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolve (ResolvedPom.java:299)
    at org.openrewrite.maven.tree.ResolvedPom.resolve (ResolvedPom.java:144)
    at org.openrewrite.maven.tree.Pom.resolve (Pom.java:104)
    at org.openrewrite.maven.MavenParser.parseInputs (MavenParser.java:105)
    at org.openrewrite.Parser.parse (Parser.java:41)
    at org.openrewrite.maven.MavenMojoProjectParser.parseMaven (MavenMojoProjectParser.java:363)
    at org.openrewrite.maven.AbstractRewriteMojo.listResults (AbstractRewriteMojo.java:276)
    at org.openrewrite.maven.AbstractRewriteRunMojo.execute (AbstractRewriteRunMojo.java:54)
    [...]
```
