### ISSUE TITLE
org.openrewrite.staticanalysis.RemoveUnusedLocalVariables failing because an optional property is not defined

### ISSUE THREAD

**Issue by FVenneri** [openrewrite/rewrite#4481] opened 2024-09-10 09:00 UTC
## What version of OpenRewrite are you using?

I am using the 

- OpenRewrite v6.22.0
- rewrite-static-analysis v1.15.0
- rewrite-rewrite-migrate-java v2.23.0

## How are you running OpenRewrite?

I am using the Gradle (Kotlin DSL) plugin, my project is a multi-module project with no sources in the root, the root is a container only.
```
dependencies {
    rewrite("org.openrewrite.recipe:rewrite-static-analysis:1.15.0")
    rewrite("org.openrewrite.recipe:rewrite-migrate-java:2.23.0")
}

configure<RewriteExtension> {
    activeRecipes.clear()
    activeRecipes.addAll(listOf(
            "org.openrewrite.staticanalysis.FinalizeMethodArguments"
            ,"org.openrewrite.staticanalysis.FinalizePrivateFields"
            ,"org.openrewrite.staticanalysis.FinalizeLocalVariables"
            ,"org.openrewrite.staticanalysis.RemoveUnusedLocalVariables"
            ,"org.openrewrite.staticanalysis.RemoveUnusedPrivateMethods"
            ,"org.openrewrite.staticanalysis.RemoveUnusedPrivateFields"
            ,"org.openrewrite.java.migrate.lang.var.UseVarForPrimitive"
            ,"org.openrewrite.java.migrate.lang.var.UseVarForGenericsConstructors"
            ,"org.openrewrite.java.RemoveUnusedImports"
            ,"org.openrewrite.java.format.Spaces"
    ))
}

tasks.register("rewriteRunSpecific") {
    doLast {
        val rewriteFolders: String? = project.findProperty("rewriteFolders") as String?
        rewriteFolders?.let {
            val folder = it.trim().split(",")
            project.extensions.findByType(SourceSetContainer::class.java)?.named("main")?.configure {
                java.srcDirs(folder)
            }
        }
    }
}

tasks.named("rewriteRun").configure {
    dependsOn("rewriteRunSpecific")
}
```
The configuration might seem odd, but it's optimised to run on a limited amount of files instead of the whole project.

## What is the smallest, simplest way to reproduce the problem?

I get it every time I run the `rewriteRun` task, but it's happening from a few days, before it was OK.

## What did you expect to see?
No errors!

## What did you see instead?
```
> Task :rewriteRun
Validating active recipes
Recipe validation error in RemoveUnusedLocalVariables.ignoreVariablesNamed: is required
Recipe validation error in RemoveUnusedLocalVariables.ignoreVariablesNamed: is required
Recipe validation error in RemoveUnusedLocalVariables.ignoreVariablesNamed: is required
Recipe validation errors detected as part of one or more activeRecipe(s). Execution will continue regardless.
```

## What is the full stack trace of any errors you encountered?

The debug output is too long and it doesn't contain much of useful information
```
> Configure project :myproject-documentation
...

> Task :rewriteRun
Validating active recipes
Recipe validation error in RemoveUnusedLocalVariables.ignoreVariablesNamed: is required
Recipe validation error in RemoveUnusedLocalVariables.ignoreVariablesNamed: is required
Recipe validation error in RemoveUnusedLocalVariables.ignoreVariablesNamed: is required
Recipe validation errors detected as part of one or more activeRecipe(s). Execution will continue regardless.
Scanning sources in project :myproject
Using active styles []
Scanning sources in project :myproject-documentation
Using active styles []
Scanning sources in project :myproject-testutil
Using active styles []
Scanning sources in project :
Using active styles []
All sources parsed, running active recipes: org.openrewrite.staticanalysis.FinalizeMethodArguments, org.openrewrite.staticanalysis.FinalizePrivateFields, org.openrewrite.staticanalysis.FinalizeLocalVariables, org.openrewrite.staticanalysis.RemoveUnusedLocalVariables, org.openrewrite.staticanalysis.RemoveUnusedPrivateMethods, org.openrewrite.staticanalysis.RemoveUnusedPrivateFields, org.openrewrite.java.migrate.lang.var.UseVarForPrimitive, org.openrewrite.java.migrate.lang.var.UseVarForGenericsConstructors, org.openrewrite.java.RemoveUnusedImports, org.openrewrite.java.format.Spaces

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 17s
16 actionable tasks: 2 executed, 14 up-to-date
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Maybe, but I have limited amount of time for it...

**Comment by FVenneri** [comment] 2024-09-10 09:06
I am trying to define this property through the yml file, but I didn't find a way to detect it, I have tried putting the file `rewrite.yml` and `openrewrite.yml` in the root folder, even copying it in all the submodules, but still it's not getting detected.

Manually setting the configFile from the `build.gradle.kts` didn't work either, and I ran out of options. 

Any help with this?

**Comment by timtebeek** [comment] 2024-09-10 10:22
Thanks for the detailed report! This looks to be a duplicate of this earlier issue related to that specific recipe:
- https://github.com/openrewrite/rewrite-static-analysis/issues/333
- https://github.com/openrewrite/rewrite-static-analysis/commit/397e325a7d236e706dfc92a248a4d9d85e0573b3

We'll do a new release tomorrow that includes this fix; until then you can use [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions).

**Closed by timtebeek** 2024-09-10 10:22 UTC
Labels: bug

**Comment by timtebeek** [comment] 2024-09-10 10:24
Sorry that this has caused you some time to debug the issue; thanks for reporting it here! We release every two weeks, which is usually quick enough, but in this case perhaps a patch release of rewrite-static-analysis would have been warranted, seeing how the issue was discovered the day after the release.
