### ISSUE TITLE
Add a way to exclude some recipes from a compound recipe and/or from rewrite execution

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1714] opened 2022-04-26 10:28 UTC
E.g. I would like to execute on my code this compound recipe https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/resources/META-INF/rewrite/static-analysis-cleanup.yml#L18 but exclude org.openrewrite.java.cleanup.HiddenField because it doesn't fit with the style decided by the team.

Currently I can only make my own copy of the compound recipe, but I won't benefit from upstream update.

A way to achieve that could to add an extra `excludedRecipeList` field in compound recipes : 
```yml
type: specs.openrewrite.org/v1beta/recipe
name: MyCustomCommonStaticAnalysis
recipeList:
  - org.openrewrite.java.cleanup.CommonStaticAnalysis
excludedRecipeList:
  - org.openrewrite.java.cleanup.HiddenField
```

There could also be an extra configuration option in maven plugin configuration to declare recipes to excludes from execution.

**Comment by tkvangorder** [comment] 2022-04-27 19:19
This work may be a duplicate of #1596

**Comment by murdos** [comment] 2022-04-27 20:17
Both issues are similar, but don't have the same scope: #1596 is for excluding recipe(s) on a specific line or a class in source code, and the proposed solution requires to modify source code.

This issue is about the way to refine a compound recipe, and to configure rewrite plugin to ignore some recipes: the new recipe or the plugin configuration could be shared and applied on any source code, and don't require changing source code beforehand.

**Comment by traceyyoshima** [comment] 2022-04-28 22:45
Hi @murdos, I discussed the draft PR I opened with the team and we decided to not add exclusions. Details about some of the complexities may be found [here](https://github.com/openrewrite/rewrite/issues/1731).

In the meantime, I recommend copying the recipe and removing `org.openrewrite.java.cleanup.HiddenField`.
Hopefully, this helps, sorry I couldn't add the exclusion list for you.

**Comment by traceyyoshima** [comment] 2022-04-29 17:19
Hi @murdos! I'd like to check in to see if there is any way we could improve `HiddenField` to meet your needs or if it's generally something that is undesired.

> `org.openrewrite.java.cleanup.HiddenField because it doesn't fit with the style decided by the team.`

We could add configurations to fit your needs so that specific changes you don't like won't happen.
Would additional configurations to `HiddenField` help you?

**Comment by okundzich** [comment] 2022-04-29 19:32
we can also remove this recipe from the bundle as i understand a lot of people do not like this style.

**Closed** 2022-04-29 21:22 UTC
Labels: question, wontfix

**Comment by murdos** [comment] 2022-05-01 21:25
@traceyyoshima: I'm not sure adding more configuration would help.
Our main issue is that we use methods that are variant of setters (`withField(String value)`, or just `field(String value)` e.g. for a String field):
```java
public class Foo {
  private String field;

  public Foo field(String field) {
    this.field = field;
    return this;
  }
```
These methods always have an **unambiguous** statement like `this.field = field;` so renaming parameter doesn't really make sense.

Thanks for having removed the recipe from `CommonStaticAnalysis`!

**Comment by traceyyoshima** [comment] 2022-05-02 17:21
> I'm not sure adding more configuration would help.
> Our main issue is that we use methods that are variant of setters (withField(String value), or just field(String value)

Thank you very much, that is helpful information and makes sense.



> Thanks for having removed the recipe from `CommonStaticAnalysis`!

You're welcome, thank you for the report!
