### ISSUE TITLE
Build is extremely brittle due to usage of latest.release

### ISSUE THREAD

**Issue by gsmet** [openrewrite/rewrite#1508] opened 2022-03-27 09:41 UTC
Hi,

I had two build issues trying to build OpenRewrite lately:
- the new Jackson BOM having problems with Gradle: https://github.com/FasterXML/jackson-databind/issues/3428
- and this Sunday morning, Gradle can't downloads the Gradle plugins probably due to a Gradle outage

This, without any change on my side.

This all boils down to the massive use of `latest.release` as the version of dependencies in the codebase which makes builds non reproducible and very brittle as soon as the latest release has problems or incompatibility issues with the codebase.
Wondering if it would be better to switch to hardcoded versions and using Dependabot to suggest the updates automatically?

That should make the builds more solid and at least a build of the exact same code would lead to the same result from one day to another.

**Comment by shanman190** [comment] 2022-03-27 20:20
Related #1484

**Comment by tkvangorder** [comment] 2022-03-28 17:59
Going to close this issue as a duplicate of #1484

**Comment by jkschneider** [comment] 2022-03-28 18:06
We can commit to once-a-day [dependency locking](https://docs.gradle.org/current/userguide/dependency_locking.html#enabling_locking_on_configurations), but we will not rely on Dependabot as it is not nearly sophisticated enough to deal with Gradle dependency management. We can craft a Github action workflow to attempt to update dependencies once a day, and if the tests pass, commit the new lock.

**Closed** 2022-03-28 18:07 UTC
