### ISSUE TITLE
Equality operators should not be used in "for" loop termination conditions

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#818] opened 2021-07-21 17:03 UTC
see: https://rules.sonarsource.com/java/RSPEC-888

>Testing for loop termination using an equality operator (== and !=) is dangerous, because it could set up an infinite loop. Using a broader relational operator instead casts a wider net, and makes it harder (but not impossible) to accidentally write an infinite loop.

**Comment by jkschneider** [comment] 2021-07-23 23:44
Duplicate of #811

**Closed by jkschneider** 2021-07-23 23:44 UTC
Labels: design-partner-6, enhancement
