### ISSUE TITLE
JavaParser does not maintain `JCIdent.sym.owner` symbol when building `JIdentifier` objects for primitive types.

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#594] opened 2021-05-27 22:18 UTC
JavaParser does not maintain `JCIdent.sym.owner` symbol when building `JIdentifier` objects for primitive types.  
This results in a bug where `RemoveUnusedImports` removes referenced static imports for primitive types. 

```java
import static java.sql.ResultSet.TYPE_FORWARD_ONLY;
public class A {
    int t = TYPE_FORWARD_ONLY;
}
```
Java11ParserVisitor:  
notice the `JCVariableDecl.init.sym.ower` is `java.sql.ResultSet`
![image](https://user-images.githubusercontent.com/22326988/119902249-d3896e00-befb-11eb-8bdf-7d2f1bc2a6b6.png)

JavaVisitor:
notice the associated `NamedVariable.initializer.identifier` is type `Int`. 
![image](https://user-images.githubusercontent.com/22326988/119902730-86f26280-befc-11eb-89e0-500a55d8aca8.png)

**Comment by jkschneider** [comment] 2021-05-28 00:57
Duplicate of #580

**Closed** 2021-05-28 00:57 UTC
Labels: bug, duplicate
