### ISSUE TITLE
Add "ast download" to `assert(Unc|C)hanged` test harness

### ISSUE THREAD

**Issue by kmccarp** [openrewrite/rewrite#558] opened 2021-05-19 17:23 UTC
In the Moderne SaaS we have the ability, from the diff view of a recipe run, to copy a link to a JSON-serialized AST for the file (taken from before the recipe's run).

Add an argument to the `assert(Unc|Changed)` test harness to allow passing this URL and a bearer token, which would then download the AST and use it as the "before" of the unit test.

These unit tests are designed to be short-lived to identify a problem and then be replaced with a more permanent unit test.

**Comment by jkschneider** [comment] 2021-06-02 05:06
Fixed with 7bba0687d8fc2eb6e91c95ea3687b360b127099e

**Comment by jkschneider** [comment] 2021-06-02 05:06
Duplicate of #606

**Closed by jkschneider** 2021-06-02 05:06 UTC
Labels: enhancement
