### ISSUE TITLE
Migrate from Gradle Enterprise gradle plugin to Develocity plugin 

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#4135] opened 2024-04-15 09:24 UTC
## What problem are you trying to solve?

> Starting with version 3.17, the plugin is available under the “Develocity” brand. Please see the [Develocity Gradle Plugin User Manual](https://docs.gradle.com/enterprise/gradle-plugin/current) for the latest documentation. Several core functionalities have been deprecated with the rebranding and will be removed in a future plugin version. Therefore, upgrading to the 3.17+ version of the plugin requires more than just updating the version number.

> Start by updating the plugin’s version to 3.17 and changing the plugin ID to com.gradle.develocity. If you are using the common-custom-user-data-gradle-plugin, update the plugin’s version to 2.0. After running a simple task like ./gradlew help you will be informed about the usage of the deprecated APIs:

> Most of the violations can be fixed by replacing references of gradleEnterprise with develocity. Some APIs have been replaced by more descriptive and idiomatic alternatives. In this example, those APIs are taskInputFiles and publishAlways(). See [Breaking API changes](https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_replaced_apis) section for this and other examples. After these changes, your build script should look like the following:

https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_migration

**Comment by Bananeweizen** [comment] 2024-05-21 17:53
duplicate of #4134. @timtebeek looks like you had a network glitch

**Comment by timtebeek** [comment] 2024-05-21 18:01
ah no they are subtly different; one is for Maven and the other is for Gradle; Both need their own recipe for the migration. Thanks for checking though!

**Closed** 2024-07-11 21:43 UTC
Labels: recipe
