### ISSUE TITLE
JavaDoc parsing messes up @{link} that is spread over multiple lines

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#1696] opened 2022-04-21 02:31 UTC
![image](https://user-images.githubusercontent.com/8549033/164359817-9e466faa-161f-4d03-93cc-87444b5b9a67.png)

Note this is from parsing and printing back out alone, no Recipe changed these lines

**Comment by traceyyoshima** [comment] 2022-04-22 15:49
Closing the issue as a duplicate of #1078.

**Closed by traceyyoshima** 2022-04-22 15:49 UTC
Labels: bug, duplicate
