### ISSUE TITLE
Update `org.openrewrite.java.format.Spaces` to not make breaking changes on gradle files

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite#3566] opened 2023-09-27 02:11 UTC
Update `org.openrewrite.java.format.Spaces` to not make breaking changes on gradle files like [this](https://github.com/openrewrite/rewrite-gradle-tooling-model/commit/21dc3371d6cd198db5b9cc7aec1e3fb49a712a5b#diff-3de4e8a834076bed991897641edae619f6b783e6e9366058a3edc20ccf2d8138L37)

Example:
```diff
-allprojects {
-   apply plugin: x
+allprojects{
+   applyplugin: x
}
```

**Comment by shanman190** [comment] 2023-09-29 04:57
@kunli2 , this is a duplicate of https://github.com/openrewrite/rewrite/issues/3030.

**Comment by knutwannheden** [comment] 2023-09-29 05:20
Fixed by https://github.com/openrewrite/rewrite/commit/a60b83a92c789ee838a0caed02ca74774141930b

**Closed by knutwannheden** 2023-09-29 05:20 UTC
Labels: bug

**Comment by knutwannheden** [comment] 2023-09-29 05:22
Thanks for noticing, @shanman190 .
