### ISSUE TITLE
MavenParser fails to parse pom with broken formatting

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite#3922] opened 2024-01-16 10:20 UTC
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.13.2

## How are you running OpenRewrite?

I use the `MavenParser` programmatically.

## What is the smallest, simplest way to reproduce the problem?

```java
class MavenParserFailsOnBrokenFormat {

		// @formatter:off
		public static final String BROKEN_FORMAT =
			    """
			    <?xml version="1.0" encoding="UTF-8"?>
			    <project xmlns="http://maven.apache.org/POM/4.0.0"
			          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
			     <modelVersion>4.0.0</modelVersion>
			     <groupId>org.example</groupId>
			     <artifactId>artifact</artifactId>
			     <version>0.1.0-SNAPSHOT</version>
			</project>		
			""";

		public static final String VALID_FORMAT =
				"""
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                     <modelVersion>4.0.0</modelVersion>
                     <groupId>org.example</groupId>
                     <artifactId>artifact</artifactId>
                     <version>0.1.0-SNAPSHOT</version>
                </project>		
                """;
		// @formatter:on

		@Test
		@DisplayName("should not fail with broken formatting")
		@ExpectedToFail("Broken format fails the parse")
		void shouldNotFailWithBrokenFormatting() {
			SourceFile sourceFile = MavenParser.builder().build().parse(BROKEN_FORMAT)
					.toList()
					.get(0);
			assertThat(sourceFile).isInstanceOf(Xml.Document.class);
		}

		@Test
		@DisplayName("should not fail with broken formatting")
		void shouldNotFailWithBrokenFormatting2() {
			// @formatter:off
			SourceFile sourceFile = MavenParser.builder().build().parse(VALID_FORMAT)
					.toList()
					.get(0);

			assertThat(sourceFile).isInstanceOf(Xml.Document.class);
			// @formatter:on
		}
	}```
```

## What did you expect to see?

See assertions in test

## What did you see instead?

See assertions in test

## What is the full stack trace of any errors you encountered?

failing test

**Comment by timtebeek** [comment] 2024-01-16 10:55
Thanks for reporting this issue! Indeed confirmed with this slight variation added to RawPomTest
https://github.com/openrewrite/rewrite/blob/f34b695123eccd83cc16b04bbb04daa6c97e609e/rewrite-maven/src/test/java/org/openrewrite/maven/internal/RawPomTest.java#L30
```java
@Test
void leadingWhitespace() {
    //language=xml
    String xmlWithLeadingWhitespace = """
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
           <modelVersion>4.0.0</modelVersion>
           <groupId>org.example</groupId>
           <artifactId>artifact</artifactId>
           <version>0.1.0-SNAPSHOT</version>
      </project>
      """;
    RawPom pom = RawPom.parse(new ByteArrayInputStream(xmlWithLeadingWhitespace.getBytes()), null);
    assertThat(pom.getGroupId()).isEqualTo("org.example");
}
```

Which fails with
```
java.io.UncheckedIOException: Failed to parse pom

	at org.openrewrite.maven.internal.RawPom.parse(RawPom.java:113)
	at org.openrewrite.maven.internal.RawPomTest.leadingWhitespace(RawPomTest.java:578)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [1,9]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:734)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:600)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:30)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1262)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3883)
	at org.openrewrite.maven.internal.RawPom.parse(RawPom.java:107)
	... 4 more
Caused by: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [1,9]
	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:634)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:504)
	at com.ctc.wstx.sr.BasicStreamReader.readPIPrimary(BasicStreamReader.java:4025)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2156)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:729)
	... 9 more
```
For reference: here's how we configure the XmlMapper
https://github.com/openrewrite/rewrite/blob/03c458404073082275a752063887c188d213afbe/rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenXmlMapper.java#L45-L67

**Comment by timtebeek** [comment] 2024-01-16 10:56
Not yet sure what the fix would be; probably a small tweak to the configured mapper provided you know exactly what to change.

**Comment by knutwannheden** [comment] 2024-01-16 14:35
Looks like there would be a way to configure the corresponding property in Jackson (https://cowtowncoder.medium.com/configuring-woodstox-xml-parser-woodstox-specific-properties-1ce5030a5173), but based on other reports I find when I google for something like "xml whitespace before prolog" and looking at the XML specification (https://www.w3.org/TR/xml/#sec-well-formed), I get the impression that whitespace before the prolog is not valid and causing problems with many other XML parsers as well. So I would be inclined to close this issue.

@fabapp2 Can you tell us a bit more about your use case?

**Closed** 2024-05-07 07:15 UTC
Labels: bug
