### ISSUE TITLE
Annotation Spaces Formatting does not remove space before first argument

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#245] opened 2021-02-08 23:25 UTC
The AnnotationFormatting for arguments is not working when the first argument starts with a space
```
pre-formatted:
@Foo( "/user/{userId}/edit")
expected format:
@Foo("/user/{userId}/edit")
```

**Comment by jkschneider** [comment] 2021-02-10 20:08
Duplicate of #149

**Closed by jkschneider** 2021-02-10 20:08 UTC
