### ISSUE TITLE
When specifing a JavaParser's classpath from byte[][], usage of classes in the default package cannot be resolved

### ISSUE THREAD

**Issue by Col-E** [openrewrite/rewrite#3222] opened 2023-05-09 04:46 UTC
## The setup

There are 3 classes in the default package:

```java
public interface InterfaceA {
    void methodA();
}

public interface InterfaceB {
    void methodA();

    void methodB();
}

public class User implements InterfaceA, InterfaceB {
    @Override
    public void methodA() {}

    @Override
    public void methodB() {}
}
```

The `JavaParser` instance can be specified in two ways:
```java
// Classpath from compiled class files, fails to acknowledge classes in the default package
public static JavaParser prepareBinaryCP(byte[][] classpath) {
    JavaParser parser = JavaParser.fromJavaVersion()
            .classpath(classpath)
            .build();
    return wrap(parser);
}

// Classpath from directories (in our case, a single path pointing to the default package containing our sources)
public static JavaParser prepareSourceDirCP(Collection<Path> classpath) {
    JavaParser parser = JavaParser.fromJavaVersion()
            .classpath(classpath)
            .build();
    return wrap(parser);
}
````

Using `org.openrewrite:rewrite-java-17` attempting to resolve the `J.Identifier` type of the classes referened in `implements InterfaceA, InterfaceB` yields different results based on the type of classpath.

The parser created from `prepareBinaryCP` fails, and tells you the types are `Unknown`. The parser from `prepareSourceDirCP` succeeds and reports `InterfaceA` and `InterfaceB` respectively.

Attached you can find a gradle project with the full setup demonstrating this behavior.

[demo_project.zip](https://github.com/openrewrite/rewrite/files/11427326/demo_project.zip)

**Comment by timtebeek** [comment] 2023-05-15 17:23
That's quite unfortunate @Col-E ! Thanks for reporting it here. Appreciate the time you've taken to produce the demo project.zip.
It took me a while to bring that down to this reproducing test: https://github.com/openrewrite/rewrite/pull/3245

Some simplifications that I've applied are:
 - Not have a method `methodA` in both `InterfaceA` and `InterfaceB`.
 - Move `InterfaceA` to package `example`, and reference that from `User`.
 - Do not provide a compiled `User` class to `.classpath(byte[][])`.
 - Limit reproduction to a single unit test.

Would you agree that covers the same case as what you've reported here?

**Comment by Col-E** [comment] 2023-05-15 18:28
The test in #3245 serves the purpose of this bug report perfectly well.

I'd like to verify after this gets solved that this also does not affect resolving of fields and method declarations belonging to classes in the default package, but since the class itself couldn't be resolved there was no way to verify that in my demo.

Perhaps a follow-up test to ensure this works as intended is warranted?

**Comment by timtebeek** [comment] 2023-05-15 21:33
I've gone ahead and merged the test as it is, such that you can explore from the main branch yourself if you want to, and start a subsequent pull request if that helps. Signing off since it's close to midnight here. I've got some travel ahead for the rest of the week. Will keep an eye on this one but not sure I'll be able to resolve this immediately.

**Comment by timtebeek** [comment] 2023-05-16 09:00
Think I've pinned it down to https://github.com/openrewrite/rewrite/pull/3249 ; feel free to test locally with `./gradlew publishToMavenLocal` as well, pending a merge.

**Closed** 2023-05-16 09:51 UTC
Labels: bug

**Comment by timtebeek** [comment] 2023-05-16 09:53
You can try out this change through [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions). Hope that helps!

**Comment by Col-E** [comment] 2023-05-16 23:19
Thanks for the quick fix :+1:

**Comment by timtebeek** [comment] 2023-05-17 08:16
You're welcome! Glad it was relatively easy to do. Curious about your use case for `byte[][]` though; are you able to give a bit of background to your use case there? Just so we can support it better going forward.

**Comment by timtebeek** [comment] 2023-05-22 10:40
Thanks for sharing your use case! It's indeed a bit out of scope for what we'd thought to cover, but you're welcome to use our internals if that helps. Do note that we are working on an 8.0 release, which might break some of those internals. You might already want to switch to a local copy of https://github.com/openrewrite/rewrite/tree/large-repositories . And then I suppose we just have to hope your use of OpenRewrite for code de-obfuscation does not end up hurting us both. ;)
